aplicacion:
  nombre: Mi aplicacion
  version: 2.0
  entorno: desarrollo
  due_date: 2015-11-08T11:30:05.905898

base:
  tipo: mysql
  host: localhost
  puerto: 8080
  nombre: mi base de datos
  usuario: mi usuario
  contrasena: mi contrasena

usuarios:
  nombre: Juan Pérez
  edad: 30
  sexo: masculino
  hobbies: programación, lectura, deporte